### ISSUE TITLE
Replace original branding with flexible vanilla, versioning

### ISSUE THREAD

**Issue by hifi** [TheAssemblyArmada/Vanilla-Conquer#14]
We can't "ship" with original game names in the window titles etc.

We should use `PRODUCT_NAME` etc. defines that can be overridden and changed. Git based revision versioning should also be included.

**Comment by OmniBlade** [comment]
#73 has addressed parts of this issue, still need to adjust the info provided in the window title.

**Comment by hifi** [comment]
I consider this fixed now. The games both identify as "Vanilla Conquer" right now but we can live with it for now.
