### ISSUE TITLE
-fpack-struct=1 causes problems

### ISSUE THREAD

**Issue by cg9999** [TheAssemblyArmada/Vanilla-Conquer#191]
It seems -fpack-struct=1 defined in the CXX_FLAGS causes problems with external system calls on linux.

I get stack smashing at file_posix.cpp Find_File_Data_Posix::FindNextWithFilter()
during the stat call 
`if (stat(DirEntry->d_name, &buf) != 0) {`

when stepping through the code in gdb, the stack canary get overwritten during this call.

when investigating this issue, I found out the size of the stat buffer is 84 when -fpack-struct=1 is used, otherwise it is 88.

I made a small reproducer which causes stack smashing when compiled with -m32 -fpack-struct=1

```
#include <sys/stat.h>
#include <dirent.h>
#include <stdio.h>
#include <unistd.h>

DIR* Directory;
struct dirent* DirEntry;
 
int blah() {
        DirEntry = readdir(Directory);

        struct stat buf = {0};
        printf("Size of stat buffer: %d @ %x  filename: %s\n", sizeof(buf), &buf, DirEntry->d_name);
        stat(DirEntry->d_name, &buf);
        return 0;
}


int main() {
        char cwd[PATH_MAX] = {0};
        getcwd(cwd, PATH_MAX);
        Directory = opendir(cwd);
        blah();
}
```

There may be other places where this is happening, but it does not happen to overwrite the stack canary and causes silent corruption

**Comment by OmniBlade** [comment]
Thanks for this, we are unpicking the requirement for struct packing as part of our drive to cleanup and make the code more portable anyway so hopefully issues like this will go away when we aren't using it anymore.

**Comment by hifi** [comment]
A 64-bit build doesn't add that flag anymore. TD should be in pretty good working order without it.

**Comment by OmniBlade** [comment]
#197 has been merged which should fix this, could you confirm?

**Comment by cg9999** [comment]
I can confirm that that the 64 bit build now works and fixes this issue, which occurs when trying to display the save/load dialog.

Game can now be saved, but there seems to be a different bug, causing crash when trying to load a saved game. I have not yet investigated this further.

**Comment by hifi** [comment]
Okay, thanks, I'll close this.
