### ISSUE TITLE
[Linux] "Command & Conquer is unable to detect your CD ROM drive"

### ISSUE THREAD

**Issue by hazelnot** [TheAssemblyArmada/Vanilla-Conquer#194]
I built the Linux executable, installed the game from the ISOs, kept them mounted and tried to run vanillaconquer, but all I get is an error message saying "Command & Conquer is unable to detect your CD ROM drive" in the game window, and the terminal log ends with 

```
C&C95 - About to search for CD drives
Prog_End()C&C95 - About to call Sound_End.
C&C95 - Returned from Sound_End.
C&C95 - Deleting mouse object.
C&C95 - Deleting palette object.
```

**Comment by OmniBlade** [comment]
CD detection code is windows only, I believe you have to use the -CD command line option to set the path to be searched for the CD contents which should work when set to the CD mount point.

We will probably look at removing the CD handling code in the future once we have code in place to replace it with locally copied data.

Its good to see people trying out the preliminary linux builds, once we are happy that most of the gotchas like this are solved we will look at doing a proper release and probably announce it more widely.

**Comment by hifi** [comment]
You also need to make sure all the required files are in uppercase as we don't yet have a system that loads them properly on a case sensitive filesystem. Most or possibly all of them are uppercase by default (including extension).

**Comment by hazelnot** [comment]
Hmm, using -CD seems to do absolutely nothing. Maybe I'm using it wrong? I used `./vanillatd -CD "/run/media/hazelnot/GDI95"`, which is where the ISO is mounted.

Edit: wait, are you waying the files on the _CD_ need to be all uppercase? Cause I don't know how I can achieve that.

**Comment by capsterx** [comment]
you could
cd /run/media/hazelnot/GDI95
/path/to/vanillatd -CD.
and I think that would work

**Comment by hifi** [comment]
CD support has been completely removed so this isn't an issue anymore.
