### ISSUE TITLE
Sidebar icons after the first row are only clickable on the top part

### ISSUE THREAD

**Issue by hazelnot** [TheAssemblyArmada/Vanilla-Conquer#195]
In Linux at least. Here's some screenshots.

![Screenshot from 2020-11-30 17-28-04](https://user-images.githubusercontent.com/10992973/100629194-ae8fb600-3331-11eb-9b7c-5b34fa53b888.png)

![Screenshot from 2020-11-30 17-28-49](https://user-images.githubusercontent.com/10992973/100629190-ad5e8900-3331-11eb-9375-38927941413f.png)

**Comment by hifi** [comment]
This happens with the current Win32 build as well so it's not an SDL specific issue.

**Comment by hifi** [comment]
```
223ad5c68e130cca9ac2de3356c59443d7b35f5d is the first bad commit
commit 223ad5c68e130cca9ac2de3356c59443d7b35f5d
Author: tomsons26 <tomsons26lv@gmail.com>
Date:   Fri Oct 23 19:54:32 2020 +0300

    Brings SidebarClass a bit more line with RA, implements Zoom_Mode_Control.
```
