### ISSUE TITLE
VanillaTD Skirmish mode

### ISSUE THREAD

**Issue by OmniBlade** [TheAssemblyArmada/Vanilla-Conquer#203]
The Remaster build supports a skirmish mode for TD via the glyphx frontend, but the vanilla menu system currently has no way of going into skirmish mode. In RA the Serial menu pulled double duty and also acted as the skirmish menu which is now its sole role. The TD menu could perhaps be refactored in a similar fashion.

**Comment by Gerwin2k** [comment]
For what it is worth. I tested a build with this skirmish mode yesterday. It worked fine. MinGW, Win32, DirectDraw.
