### ISSUE TITLE
TD corrupts CONQUER.INI on Linux

### ISSUE THREAD

**Issue by hifi** [TheAssemblyArmada/Vanilla-Conquer#209]
TD overwrites CONQUER.INI but I suspect it's an overlapping strcpy that is causing it to be corrupted.

**Comment by cg9999** [comment]
I have some overlapping mem/strcpy fixes on my ongoing valgrind debug branch. Maybe some of these are related? Should I make a pull request for these at this point?
https://github.com/cg9999/Vanilla-Conquer/tree/valgrind_fixes

**Comment by hifi** [comment]
This would probably be a good time, yeah. Getting all these small issues fixed so that we can default the debug builds to ASAN enabled would be excellent.

**Comment by OmniBlade** [comment]
@hifi Want to confirm if the valgrind fixes fixed this issue?

**Comment by hifi** [comment]
My ini file has not been corrupted anymore so I'd say this is fixed. Thanks.
