### ISSUE TITLE
64 bit support 

### ISSUE THREAD

**Issue by hifi** [TheAssemblyArmada/Vanilla-Conquer#24]

**Comment by wdigger** [comment]
64-bit version of DirectDraw don't support legacy features, at least it's impossible to set video mode in the same way as with 32-bit DirectDraw.

**Comment by hifi** [comment]
We don't need DirectDraw when SDL2 support lands. This depends on #19.

**Comment by wdigger** [comment]
It's just a reminder, so that no one wasted time trying to switch to 64-bit before removing DirectDraw.

**Comment by hifi** [comment]
This has been fixed as we do 64-bit builds by default on non-Windows, regardless if they are 100% working or not.
