### ISSUE TITLE
Add video deinterlacing options

### ISSUE THREAD

**Issue by mvdhout1992** [TheAssemblyArmada/Vanilla-Conquer#247]
The game has two unused video deinterlacing modes. They do need to be fixed in terms of graphical glitches. 

3 modes. If set to 2 videos are deinterlaced, if set to 0 they're horizontally interlaced and when set to 1 they're supposed to be vertically interlaced (though the vertical interlacing doesn't seem to work).

I suggest using the VideoInterlaceMode= keyword in REDALERT.INI under the [Options] section. as done with CnCNet patches.

**Comment by OmniBlade** [comment]
Mode 1 is horizontal line interpolation but vertical line doubling rather than leaving alternating scan lines blank and is actually hard coded to be used for the RA mission select screen. Seems a reasonable suggestion though.

**Comment by mvdhout1992** [comment]
Added by Omniblade.
