### ISSUE TITLE
[RA]movies02.mix isn't loaded when movies01.mix is loaded, causes issues with soviet FMVs with TFD

### ISSUE THREAD

**Issue by mvdhout1992** [TheAssemblyArmada/Vanilla-Conquer#257]
movies02.mix isn't loaded when movies01.mix is loaded, causes issues with soviet FMVs with TFD

This affects The First Decade where the Soviet campaign movies (stored in movies2.mix) would never play because TFD Red Alert 1 comes with both MIX files.

**Comment by mvdhout1992** [comment]
This should be fixed with Omniblade's changes to MIX loading code. But I don't got TFD to test.

**Comment by hifi** [comment]
I have TFD on my shelf. I plan to have a data set of every release (I think I have TUC on Origin) I own installed for testing purposes. 

Will try soon.

**Comment by hifi** [comment]
Tested this now works with TFD. Forgot to close this issue.
