### ISSUE TITLE
Implement proper no-cd solution for both games

### ISSUE THREAD

**Issue by hifi** [TheAssemblyArmada/Vanilla-Conquer#291]
We currently require the user to copy mix files from the CD they want to play and use the `-CD.` argument to skip CD search.

I suggest we modify the CD nagger dialog code to look for predetermined directories within the game data directory for CD stuff and present a list of CDs to play from depending what directories were found. If we find `MAIN.MIX` in the game directory itself we should skip this dialog and assume `-CD.` which makes the old and expected behavior the default which should work with all sorts of repacks of the data. This works with the demo files as well.

So for example in RA we could look for directories like ALLIED, SOVIET, AFTERMATH etc. and present the ones we find in a dialog.

**Comment by capsterx** [comment]
I dont think this method will work.  The current code checks the CD LABEL for CD1 or CD2. 

red alert cd 1d1# find . -name "*.MIX"
./INSTALL/REDALERT.MIX
./MAIN.MIX
./SETUP/AUD.MIX
./SETUP/SETUP.MIX
ls -l MAIN.MIX 
-r-xr-xr-x 1 root root 454605294 Nov  8  1996 MAIN.MIX

red alert cd 2cd2# find . -name "*.MIX"
./INSTALL/REDALERT.MIX
./MAIN.MIX
./SETUP/AUD.MIX
./SETUP/SETUP.MIX
cd2# ls -ls MAIN.MIX 
488846 -r-xr-xr-x 1 root root 500577414 Nov  8  1996 MAIN.MIX

You would need to identify which main.mix is on each area, the md5 is the same for the other .mix files.  The rest of the files, at least for red alert soviet/allied are the same afaict.

**Comment by capsterx** [comment]
It is possible to read the cd label on linux.  I have some code that does that.  It's similar to what windows does.  For the nintendo switch I check for the search path of "<path>/CD_LABEL", where CD_LABEL is a text file of the label,  which allows the rest of the code to work correctly.  At least I assume, I have not gotten to the point where it requires one to change cds.

Using CCFileClass::Set_Search_Drives instead of using win32 api to find a cd drive.

**Comment by hifi** [comment]
I meant that the directory names itself are used to identify the CD which they represent and not the contents of them. It should work fine when we accommodate the code for that and just present them as options. This would technically also allow data mods to be loaded dynamically on launch if we make it generic enough.

**Comment by mvdhout1992** [comment]
Good ideas...main.mix for no-cd and directories in the game directory to dump the disc files in. Have the CD nagger dialog mention instructions on which directories to place cd data in.

**Comment by OmniBlade** [comment]
I plan to port and PR https://github.com/TheAssemblyArmada/Chronoshift/blob/9fd980161bb5aae1fa7d33da699570d7e61f111e/src/game/io/cd.cpp#L113 unless anyone has an objection.

**Comment by mvdhout1992** [comment]
I think making it read from directories named ALLIED, SOVIET, AFTERMATH, COUNTERSTRIKE would be better than CD1/2/2/3/4. @OmniBlade 

and in the format <gamedir>/cd_data/SOVIET/ etc

And modifying the CD nag dialog to give instructions on placing the data from cd.

**Comment by hifi** [comment]
I also think it's more clear to people what the CD names are than their numbers. So `Data/Allied` for the Allied CD. But I've addressed this issue below in a way it doesn't matter.

What if we just use "Data" as the root directory (by default) next to the game executable?

This would be good preparation for Linux packaging where we can point `Data` to a read-only place and put all shared mix files in that and use the sub directories for CD contents. It would also clean up the root directory if we can move all mix files in there optionally.

So the search path would be the executable directory (current behavior) + `Data`. Then check if any MAIN.MIX is available in those, if is, set CD path to where it was found. Should work like it currently does and support a new `Data` directory. On Linux we could have it as a build option or command line switch to force different data root directory than the executable. User data (configuration files, mods etc.) can be placed elsewhere but that is outside the scope of this issue.

If no MAIN.MIX is found, prompt for CD selection based on `Data/<any directory>`. This could be completely dynamic where the folder names are presented as found. Set CD path to whatever the user selected.

**Comment by OmniBlade** [comment]
I wouldn't use a hardcoded prefix of data, I'd just leave the default assumption (for now) that its the exe directory which is the standard setup for a standalone C&C installation, but have the data directory be configurable.

That way the CD dection code doesn't need to worry about prefixes, it just looked for allied/main.mix or whatever and its up to the path resolution code (probably in CDFileClass) to sort out where it actually is looking.

We also need a writable directory to be configurable too and to be searched first for user defined files so we don't need to make the install directory writable going forward.
