### ISSUE TITLE
Failing a mission doesn't show "MISSION FAILED"

### ISSUE THREAD

**Issue by hifi** [TheAssemblyArmada/Vanilla-Conquer#298]
First issue is due to missing Frame_Limiter call in the failed mission text rendering function and latter is probably because the VQA palette is not loaded and it's using the game palette.

All other VQAs play fine before and after a mission so this palette restoration thing only affects a failed mission.

Fast to trigger by starting first Allied scenario and running Tanya towards the tesla coil.

**Comment by hifi** [comment]
Palette issue is in expansion data, text needs the frame limiter call.

#309 closes this.

**Comment by OmniBlade** [comment]
Closing as #309 was merged.
