### ISSUE TITLE
[Suggestion] Add scrollwheel support in sidebar

### ISSUE THREAD

**Issue by hazelnot** [TheAssemblyArmada/Vanilla-Conquer#307]
I don't know how people played this back in the day, my finger hurts :stuck_out_tongue:

**Comment by hifi** [comment]
This was/is implemented in CnCNet patches. Should be fairly easy to port to vanilla and definitely a QoL change that needs to go in.

**Comment by mvdhout1992** [comment]
Agreed. It's a simple patch made by CCHyper.

https://github.com/mvdhout1992/ra303p-iran/blob/master/src/mousewheel_scrolling.asm

**Comment by OmniBlade** [comment]
Resolved in #710
