### ISSUE TITLE
[TD]Music randomizing deynsc multiplayer

### ISSUE THREAD

**Issue by mvdhout1992** [TheAssemblyArmada/Vanilla-Conquer#369]
Wrong RNG used

TODO chcek if still an issue with remaster code base

**Comment by OmniBlade** [comment]
Looks likely to still be an issue to me, both games call Sim_Random_Pick which inlines to a call to an RNG, but in RA it calls to NonCriticalRandomNumber which should only be used where it doesn't affect game state. Needs properly confirming once we have network games and fixing by updating the TD code to what RA does.

**Comment by OmniBlade** [comment]
This was fixed when networking was implemented.
