### ISSUE TITLE
Megamap Commit Reduced Tiberium Growth by 75%

### ISSUE THREAD

**Issue by ChthonVII** [TheAssemblyArmada/Vanilla-Conquer#412]
Take a look at MapClass::Logic() in map.cpp. Commit 05eb91f5e78502b5be244c22200ce58c63e6b9f2 increased MAP_CELL_TOTAL by 4x, so it now takes 4x as many ticks to complete a scan and do a growth cycle. You can get back close to the original behavior by multiplying subcount (line 1460) by 4x as well.

While I'm not aware of any off the top of my head, I suspect there are other things scattered here and there that implicitly depend on the constants changed by this commit.

**Comment by OmniBlade** [comment]
Thanks for pointing this out, I'll look at the math and try and work out how it should be calculated such that it remains mostly the same. RA does some calculation to get the appropriate value rather than it being a constant so I'll use that as a reference.

**Comment by ChthonVII** [comment]
If you just jump subcount up to 120, you will be back to taking 137 ticks to complete a cycle.

It will still be a bit different because of the following: If a cell is selected into the TiberiumGrowth or TiberiumSpread array on Frame X, then later harvested on Frame X+1, then later selected during the eventual growth cycle on Frame X+whatever, the grow/spread just fails and less tiberium is added for that cycle. By changing around when during the scan the on-the-map cells get processed, you change the odds of this happening.

I think the "modifying the odds of harvesting a would-be-grower cell mid-scan" issue is minor enough you can probably ignore it. Also, I believe the only solution is decidedly non-vanilla -- do a full scan and growth cycle every tick with the grow odds reduced to probabilistically give the same growth rate. That's what I did in [my mod (see CFELogic() near the bottom)](https://github.com/ChthonVII/CnC_Remastered_Collection/blob/master/TIBERIANDAWN/MAP.CPP), and you're free to borrow it if you like.

[Edit: Sorry! I got a bit muddle-headed there. For my mod I considered the "harvesting a would-be-grower cell mid-scan" issue as something to be eliminated entirely. If you want to preserve it exactly as it exists in the original, then you'd need to do  this: For normal sized maps, keep subcount at 30 and add some logic to jump over the 12288 cells that are only used for megamaps without incrementing subcount. For megamaps, make subcount 120.]

**Comment by OmniBlade** [comment]
All maps internally are now megamaps, the game just loads older maps into the top left corner and updates cell numbers for things like waypoints and such to the new position in the array.

**Comment by ChthonVII** [comment]
Yes, I saw that. If you wanted to fully preserve the former behavior on old maps, keep subcount at 30, jump index ahead by 64 each time it hits a multiple of 64, and jump index ahead to MAP_CELL_TOTAL when you hit cell 8191. That should keep the scan taking 137 clicks between growth cycles _AND_ keep each cell's delay between evaluation and possible use in the growth cycle consistent with the original behavior. For new maps using the extra space, make subcount 120. If you don't mind a very slight behavior change for the old maps, you can just make subcount 120 across the board and call it a day.

[Edit: Forgot to mention that every other scan is backwards, so all that jumping around would also have to be implemented upsidedown.]
