### ISSUE TITLE
[RA]Counterstrike & Aftermath enabled file check should be different

### ISSUE THREAD

**Issue by mvdhout1992** [TheAssemblyArmada/Vanilla-Conquer#433]
Currently for Counterstrike it checks for expand.mix and for Aftermath it checks for expand2.mix. I suggest changing the check so it checks for some of the files in the mix itself. For Counterstrike this could be one mission file and for Aftermath this could be tesla tank graphics (tt.shp).

@OmniBlade

**Comment by OmniBlade** [comment]
This is the original DOS mod behaviour, but its also possible to override this now from redalert.ini. I'm not sure what specifically detecting the files within gets us, any mods abusing it would have failed to work with the original as well wouldn't they?
