### ISSUE TITLE
Cursor not visible in Remaster TD before alt-tab

### ISSUE THREAD

**Issue by hifi** [TheAssemblyArmada/Vanilla-Conquer#44]
This seems like a regression as it was working way back in the start.

Reproducible at least with mingw.

**Comment by hifi** [comment]
```
$ git bisect bad
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
072bc28d00dd102e0ce0d08b11190ca0d581575f
0ab9a07b4dfe30bb6f5a6786be212537f8f7c89b
ee3f604e632cc68eda5b87f2a4c7409e35cc99e3
We cannot bisect more!
```

Ping @wdigger, I could not run TD with all of these commits but one of them broke the cursor. Any idea?

**Comment by hifi** [comment]
Looking at the commits only the big move/merge can be the breaking one.

**Comment by hifi** [comment]
Okay, reverting 0ab9a07b4dfe30bb6f5a6786be212537f8f7c89b indeed fixes the cursor issue.

**Comment by wdigger** [comment]
Hm... I can see cursor as expected.

**Comment by hifi** [comment]
Can you see the building placement shadow? It's missing in both remaster TD and RA.

**Comment by wdigger** [comment]
1. I use MSVC for building. Cursor is present.
2. Got a crash on selection. Searching for issue...

**Comment by wdigger** [comment]
Where crash reports are stored? Client shows window with messages about crash info collecting, is it possible to receive those reports?

**Comment by wdigger** [comment]
Just remove this commit.
I not interested in remaster at all.

**Comment by hifi** [comment]
We just want to keep compatibility. It's a huge revert to remove all that merge work and it will would waste your effort in doing so. 

It would be better to find the issue and fix it.

**Comment by wdigger** [comment]
I can't see other options without debugger. This work have no perspective in any case.

**Comment by hifi** [comment]
Partial reverts until the issue goes away is a strategy. In the future we should prefer splitting big refactors like this into smaller commits.

**Comment by wdigger** [comment]
And use this strategy all the time? Usually developers use debugger and other tools for their work but not "strategy" ;)
Revert?

**Comment by hifi** [comment]
You can attach a debugger to the Remaster after the latest patch. I was just trying to say that it's possible to bisect the commit itself by reverting small parts of it and trying to find the _changeset_ within the commit that caused the issue.

If you have no patience you don't need to work on this.

**Comment by wdigger** [comment]
This commit is so big cause most of changes are linked. Changes mainly in headers.
I have no success with attaching, do you have an information about working solution?

I have patience for another target. Crossplatform game for example. But your way is absolutely in other direction :(

**Comment by hifi** [comment]
#46 fixes the Remaster issue from my limited testing.

We do want cross platform games - I don't even play the Remasters or use Windows for that matter. Not breaking Remaster unless it's absolutely necessary is what we want to do for now as it also serves as a _working_ testing platform for gameplay related issues.

Your work is welcome and appreciated.

https://www.youtube.com/watch?v=MnQvI4tmS_I this video may be of interest for debugging.

**Comment by wdigger** [comment]
MSVC and MinGW have a different linking procedure, I had no chance to fix it with MSVC :(

Thanks for useful info!
