### ISSUE TITLE
Strange framerate problem in SDL2/KMSDRM mode

### ISSUE THREAD

**Issue by vanfanel** [TheAssemblyArmada/Vanilla-Conquer#461]
HI there

Sorry for opening yet another issue.
I have been testing Vanilla-Conquer today in KMSDRM mode, and there's an strange problem with framerate that I can't just explain to myself. It does not happen on X11, so I must investigate.

It seems that frames "repeat" or just don't show, resulting on a very strange movement.
I am using latest Vanilla-Conquer sources, and latest SDL2 sources.

Here's the code for my KMSDRM_SwapWindow() function, in case someone wants to take a look. It's profusely commented.
https://hg.libsdl.org/SDL/file/978a7dc6dfcc/src/video/kmsdrm/SDL_kmsdrmopengles.c#l89

As you will see, I don't do another pageflip until the previous has completed. So the system is pretty solid.
Also, it doesn't return on any problem with Vanilla-Conquer: it just does what it's supposed to do.

So, is Vanilla-Conquer using some special image format?
And more importantly: is it asking for window refresh at an unusual rate and doing something with it's buffers when that fails?

**Comment by vanfanel** [comment]
Also, are you using 8bit surfaces and trying to send that to the renderer?
I have just seen that Eduke32 does something similar, an uses 8bit surfaces.

**Comment by vanfanel** [comment]
Another possible cause is that I am using ARGB8888 surfaces internally on DRM, as you can see here:

https://hg.libsdl.org/SDL/file/978a7dc6dfcc/src/video/kmsdrm/SDL_kmsdrmvideo.c#l762

What format would Vanilla-Conquer expect exactly?

**Comment by vanfanel** [comment]
Another thing to note is that KMSDRM adds ARGB8888 modes only to the modelist when video is initialized:

https://hg.libsdl.org/SDL/file/978a7dc6dfcc/src/video/kmsdrm/SDL_kmsdrmvideo.c#l937

And then, in vanilla, you recover the pixel format of the current videomode used by the window:

https://github.com/TheAssemblyArmada/Vanilla-Conquer/blob/6ded100e598fe8077fd1bf08623685d2292836af/common/video_sdl2.cpp#L166


...which simply returns the format for display->current_mode in SDL:
https://hg.libsdl.org/SDL/file/978a7dc6dfcc/src/video/SDL_video.c#l1197

So, in Vanilla, SDL_GetWindowPixelFormat(window) here:
https://github.com/TheAssemblyArmada/Vanilla-Conquer/blob/6ded100e598fe8077fd1bf08623685d2292836af/common/video_sdl2.cpp#L166
can ONLY possibly return SDL_PIXELFORMAT_ARGB8888

**Comment by vanfanel** [comment]
On yet another note, Vanilla seems to be creating an 8bpp RGB surface:

https://github.com/TheAssemblyArmada/Vanilla-Conquer/blob/6ded100e598fe8077fd1bf08623685d2292836af/common/video_sdl2.cpp#L490

...but I don't think that's what you are sending.

**Comment by hifi** [comment]
The games internally render to 8-bit surfaces and we provide them with one from SDL - it's not like it matters much, we could just `malloc()` the memory as well - but it provides an easier path to ask SDL to convert the paletted surface to whatever is the preferred format of the renderer.

This function is called every frame to flip the front buffer:

https://github.com/TheAssemblyArmada/Vanilla-Conquer/blob/6ded100e598fe8077fd1bf08623685d2292836af/common/video_sdl2.cpp#L560

It does a few things but mostly converts the internal 8-bit surface to whatever the format of the window surface is and then renders that.

**Comment by vanfanel** [comment]
@hifi The problem seems to be with the 8bit surfaces -> 32bit renderer conversion,
For example, fheroes2 works perfectly well on SDL2/KMSDRM:

https://github.com/ihhub/fheroes2/blob/6b010643f0cf00dba7aa45950f9e299726d5e983/src/engine/screen.cpp#L496

If you look there, it first tries to find out if palette modes are supported:
https://github.com/ihhub/fheroes2/blob/6b010643f0cf00dba7aa45950f9e299726d5e983/src/engine/screen.cpp#L484

And then uses an 8bpp surface ONLY if it is supported.

**Comment by hifi** [comment]
Even fheroes2 seems to do a 8->32-bit conversion per frame here:

https://github.com/ihhub/fheroes2/blob/6b010643f0cf00dba7aa45950f9e299726d5e983/src/engine/screen.cpp#L416

So it's no different except they are doing it by hand instead of using SDL_BlitSurface. One optimization they sort of have is that they create a raw 32-bit (A)RGB8 palette so mapping the colors is probably somewhat faster than with SDL_BlitSurface. If that makes a meaningful difference then we need to roll our own conversion as well but that needs to be benchmarked to warrant increased complexity.

**Comment by vanfanel** [comment]
@hifi A major difference between KMSDRM and X11, is  the return of this: 
https://github.com/TheAssemblyArmada/Vanilla-Conquer/blob/b9dd91283bd6e43f85c047a36a49dc2e007f01a1/common/video_sdl2.cpp#L166

While in X11 it returns `SDL_PIXELFORMAT_RGB888` in KMSDRM it returns `SDL_PIXELFORMAT_ARGB8888`.

This value comes from the current video mode set on the display of the SDL_window.

On KMSDRM, that can be traced to me creating all video modes with an SDL_PIXELFORMAT_ARGB8888 pixel format in:

https://hg.libsdl.org/SDL/file/a5b970d28bfd/src/video/kmsdrm/SDL_kmsdrmvideo.c#l937

Do you think that SDL returning these different formats in X11 vs KMSDRM could be related to this strange issue? I really want Vanilla-Conquer to perform as intended on KMSDRM as it's my main platform :)

EDIT: Disregard my previous questions, I have set all the available videomodes to be `SDL_PIXELFORMAT_RGB888` and I see the same problem.

**Comment by hifi** [comment]
Is that X11 vs KMSDRM on the same device or different? I can't really think of any reason how it would be different from Vanilla side of things. It just uses SDL to convert the paletted surface to whatever the window pixel format is as you've seen.

**Comment by vanfanel** [comment]
> Is that X11 vs KMSDRM on the same device or different? I can't really think of any reason how it would be different from Vanilla side of things. It just uses SDL to convert the paletted surface to whatever the window pixel format is as you've seen.

Yes, same device. I can't guess the cause, either. There are no errors on the KMSDRM side of things.

**Comment by hifi** [comment]
We had a long discussion on Discord about game ticks, frame limiter and frame skipping. We'll try to sort out some issues with the implementation and I'll get back to this issue if those make a difference when addressed.

**Comment by hifi** [comment]
You can try fiddling with #488 to see if the debug output gives you more hints or if the changed frame limiter call helps.

**Comment by hifi** [comment]
On Raspberry Pi 3B and 3B+ the game runs just fine for me _after_ I enforce the SDL2 driver to _opengles2_. Only when there are tons of explosions on the screen it stutters a bit. The allied convoy mission that's the one available in RA demo shows off the stuttering pretty easily but other than that it runs really well in 1080p.

**Comment by vanfanel** [comment]
@hifi I have just built latest sources (I had not done new builds since my last report here) and.. the game runs PERFECT now on SDL2-KMSDRM without X11! No more strange framerate issues, just pure and plain perfection :dagger: 
So yes, I believe #488 fixed things.

Sorry for taking so long to answer.. I was busy adding new features to the KMSDRM backend in SDL2 :P

**Comment by vanfanel** [comment]
@hifi If you can, could you *please* give me a small and simple roundup on what you modified regarding framerate, etc? Just in case I find games with similar problems in SDL2 KMSDRM.

EDIT: I take the only framerate-related commit is this one? 
If so, why was it affecting KMSDRM and not X11?

commit 5a7dc7c999e75e73bc5fb20c8ae813c4f2be1959
Author: Toni Spets <toni.spets@iki.fi>
Date:   Fri Jan 22 12:38:17 2021 +0200

    Call Frame_Limiter before calculating frame delay
    
    This makes the rendering time part of the per-frame delay calc
    when using SDL2 driver.

**Comment by hifi** [comment]
I'm not sure why it didn't affect X11 as much as it did KMSDRM but frame limiter being called conditionally after the game did its own delay added additional delay for each drawn frame which would've made it worse the longer the actual time was to render a frame on screen.

The `Frame_Limiter` call also does the actual flip to screen so it not being unconditionally called caused an issue where the game speed set to max would skip rendering completely on a fast system and it would've rendered only a few frames randomly on a slower system.

With slower game speed settings it would've in fact drawn two frames and wait after that which is what you saw but it would only render the latter one on screen. If the render time varies a lot or is long over all it would've made it worse as the code was not able to compensate for the first frame at all. This didn't affect higher end systems as the render time is under 1ms on such and drawing two frames instead of one didn't have any effect on performance.

I'm still trying to get KMSDRM to perform well on the Pi 1 at 1080p with nearest scaler but it doesn't seem to be possible without GLES.

**Comment by Srandista** [comment]
> 
> 
> On Raspberry Pi 3B and 3B+ the game runs just fine for me _after_ I enforce the SDL2 driver to _opengles2_. Only when there are tons of explosions on the screen it stutters a bit. The allied convoy mission that's the one available in RA demo shows off the stuttering pretty easily but other than that it runs really well in 1080p.

@hifi how can I enforce SDL2 driver to opengles2? I'm trying to play TD on my RPi 3B+, but performance out-of-the-box really isn't great.
