### ISSUE TITLE
[RA] Skirmish on demo without maps crashes

### ISSUE THREAD

**Issue by JohnsterID** [TheAssemblyArmada/Vanilla-Conquer#491]
ra95demo

1. Multiplayer Game
2. Skirmish
3. Start

Exception: C0000005.ACCESS_VIOLATION

**Comment by hifi** [comment]
Counterstrike and Aftermath dialogs have the same issue if the expansions are detected but no missions are available. The 3.03 patch on retail causes this as it includes the expand mixes.

**Comment by Gerwin2k** [comment]
Currently, both in VanillaTD and RA, the skirmish map selection interface is lacking in error detection. With the up arrow key one can seemingly select negative map index numbers. Starting a game with such a selection will cause  the game to crash.

**Comment by JohnsterID** [comment]
> With the up arrow key one can seemingly select negative map index numbers.

Seems to be for any list. Same for the music track list (steps below) and Load Mission from in-game or main menu.

1. Game Controls
2. Sound Controls
3. Up arrow key
4. Click Play Button

**Comment by JohnsterID** [comment]
Fixed by #502
