### ISSUE TITLE
[TD] Scrolling the map bottom and right direction not working

### ISSUE THREAD

**Issue by Gerwin2k** [TheAssemblyArmada/Vanilla-Conquer#493]
[TD] Scrolling the map bottom and right direction not working
This is with the VanillaTD Win32 SDL2 build d8000c0.
VanillaRA does not have this problem. VanillaTD DDraw build also does not have this problem
For testing I also deleted "conquer.ini" to make sure it was not related to my settings.

**Comment by hifi** [comment]
Sorry I didn't test TD with raw input as I really didn't think it behaves differently but it does. Opted to make raw input work the same for both games and not change how TD calculates scrolling.

**Comment by Gerwin2k** [comment]
Both games VanillaTD/RA are good now with your fix "[TD] Fix raw input scrolling #494".
Thanks!
(Together with the new SDL2 configuration options, even on Win32 it seems the SDL2 builds now became more practical than the DDraw builds. )
