### ISSUE TITLE
Repairing Barracks is free in 3.03, need to check vanilla-conquer

### ISSUE THREAD

**Issue by mvdhout1992** [TheAssemblyArmada/Vanilla-Conquer#498]
The remaster code talks about a possible fix, need to check if it's still an issue with vanilla-conquer.

**Comment by JohnsterID** [comment]
vanillara with ra95demo - SCU01EA
Damaged barracks and attempted repair. Repair was not free.

**Comment by mvdhout1992** [comment]
It's free in 3.03 and fixed in vanillaRA.

TODO investigate if there are any issues with the logic (probably not)

**Comment by mvdhout1992** [comment]
Looks to be fine so hard.
