### ISSUE TITLE
Readme remastered DLL installation instructions are wrong

### ISSUE THREAD

**Issue by mvdhout1992** [TheAssemblyArmada/Vanilla-Conquer#597]
the readme is incorrect, folder structure and ccmod.json files dont work
"version_high": 0, needs to be  "version_high": 1,
then it works
and it has CnCRemastered/ twice in the directory structure

see https://steamcommunity.com/sharedfiles/filedetails/?id=2132108399

Tested by me. Instructions didn't work. Link above did.

**Comment by OmniBlade** [comment]
I feel this is resolved since #624 was merged.
