### ISSUE TITLE
Crash when starting Nod campaign after leaving GDI one.

### ISSUE THREAD

**Issue by OmniBlade** [TheAssemblyArmada/Vanilla-Conquer#60]
Standalone build seems to crash if you exit the GDI campaign back to main menu and then try and start the Nod campaign.

**Comment by OmniBlade** [comment]
Crash is in soundio.cpp, line 1480, looked like stack was corrupt?
Need to have been in GDI first mission a bit, moved soldiers, deployed conyard and such before exiting or crash may not trigger.

**Comment by wdigger** [comment]
This sometimes happens even when you start the very first mission (not depend on selected party), it seems that it is on the party selection screen.

**Comment by wdigger** [comment]
From my own experience, I'll guess what to look for in the direction of the thread where callback from the sound driver is called.

I’m still looking, but so far I don’t see any ring buffer between the threads, this suggests the danger of such code.
