### ISSUE TITLE
[TD] Westwood logo intro does not play properly. It only stays frozen on the Westwood logo

### ISSUE THREAD

**Issue by terrorcide** [TheAssemblyArmada/Vanilla-Conquer#612]
Expected behaviour:

https://user-images.githubusercontent.com/10485456/109415611-8f94d480-79b1-11eb-9de5-893e69f69eb2.mp4

Current behaviour:

https://user-images.githubusercontent.com/10485456/109415622-9e7b8700-79b1-11eb-913b-660c70638f4f.mp4

This worked previously but one of the below commits broke this.

The first bad commit could be any of:
1b88fe872088dc4d6d6e1273dca502cfc121d990
0383819dfdd80f4ae6220f022dc9001ee5cfca2c
3409892aaf6913315ed8754c861dad3f1f8ca77c
0e48b126a2e25ad3c5d0ef961915bb4bc40835c1
85c8881da65a290713010c427b944f84c9238ba3
25ce773fad33e0687497abdfc7814f9e2a86e720
8f7bcbb6ddf601ce34e27ccf811704ebca9b3910
493cb210edf0876d94b1ff7188f5a943d5ea9561
c4dfde4d38a86a0df9b8e52fd569bcba632295a4
58207be42d3593a3b98637bd574b4b58b1b86471
fabf542a322170cefa09dc9319da71bcc09c2694
f87f5f294d40b8c2a03803136a61a9cfd3d97965

Have attached bisect log:
[bisect_log.txt](https://github.com/TheAssemblyArmada/Vanilla-Conquer/files/6056606/bisect_log.txt)

**Comment by OmniBlade** [comment]
I've tested this on the latest commits to the vanilla branch and it seems to work as expected for me. Can you confirm you still have this issue on the latest builds and if so, how you installed the game data and where from?

Thanks.

**Comment by tore29** [comment]
This might be a difference in the media used to install C&C95. Some later versions of C&C95 discs (usually ones marked with EA logos) add a logo.vga file with the animation removed to the root directory of the game. Deleting this file will cause the game to run the old version inside the mix files and thus restore the animation.

Edited to correct the incorrect reference to a "title.vqa" with the correct name "logo.vqa".

**Comment by giulianobelinassi** [comment]
The ISOs turned freeware by EA contain this modified version of title.vqa, as @tore29 said. It is not an issue with VanillaTD.

**Comment by universal963** [comment]
I presume it is logo.vqa and logo.vqp in the root directory of C&C95, not title.vqa. In fact, there are two C&C95 versions that have slight difference, one of which is the logo.vqa and logo.vqp. The older one, marked as version **1.04** in game main menu, doesn't have these files in root directory, making the game use the logo.vqa inside the movies.mix; newer version, marked as version **1.04a**, has the files in root directory, which replaced the older files to load. Thus, this question might be very simple, just remove the logo.vqa and logo.vqp in root directory, and that is all. As I know, the initial release of C&C95 should be 1.04, and later ones like freeware ISO ,The First Decade. The Ultimate Collection, and worldwide warfare pack one are 1.04a. One exception I know is the version inside the C&C3 pre-order bonus, which is 1.04.

**Comment by tore29** [comment]
@universal963 You are correct about the filenames it's logo.vqa and it's associated vqp not title.vqa. Not sure about a different version number though. Do you have some screenshots?

**Comment by universal963** [comment]
@tore29 Of course. These are the files when you installed the 1.04 version: 
![cc1104-1](https://user-images.githubusercontent.com/36097923/124284434-95790d00-db7f-11eb-834f-080eab3921ab.png)
When in game: 
![command_ _conquer-2021-07-02-21_51_43](https://user-images.githubusercontent.com/36097923/124284633-bd687080-db7f-11eb-95ae-b0336f7b5ea6.png)
![command_ _conquer-2021-07-02-22_00_46](https://user-images.githubusercontent.com/36097923/124285938-040a9a80-db81-11eb-874e-1967e9936c7f.png)
And the 1.04a one: 
![cc1104-2](https://user-images.githubusercontent.com/36097923/124285567-9bbbb900-db80-11eb-9665-0dd5603c9deb.png)
And when in game: 
![command_ _conquer-2021-07-02-21_58_49](https://user-images.githubusercontent.com/36097923/124285681-bbeb7800-db80-11eb-9d2c-3b0fa7e1de57.png)
![command_ _conquer-2021-07-02-22_01_54](https://user-images.githubusercontent.com/36097923/124286112-31574880-db81-11eb-8853-7e3a75d5f019.png)

**Comment by tore29** [comment]
@universal963 Interesting couldn't remember the version number being different.

**Comment by universal963** [comment]
@tore29 Yeah, quite unnoticeable, even the Command & Conquer wiki doesn't show this difference.

**Comment by OmniBlade** [comment]
Closing as wontfix since this is a data issue, not a vanillatd issue.
