### ISSUE TITLE
Windows XP incompatible call

### ISSUE THREAD

**Issue by Gerwin2k** [TheAssemblyArmada/Vanilla-Conquer#619]
A Windows XP incompatible call was recently introduced, which prevents both games from starting in that OS:
Shell32 - SHGetKnownFolderPath
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ee417685(v=vs.85)

There is also in red in Dependency Walker: 
MPR.dll - WNetRestoreConnectionA
But that one does not prevent running the game, it may have been there from the start.

**Comment by Gerwin2k** [comment]
My attempt to backport it. It compiles and runs. I have not tested the usage of optional files in the AppData folder.

File: common\paths_win.cpp

**Replace this:**
hr = SHGetKnownFolderPath(FOLDERID_RoamingAppData, KF_FLAG_CREATE, nullptr, &path);

**With this:**
wchar_t szPath[MAX_PATH];
hr = SHGetFolderPathW(nullptr, CSIDL_APPDATA|CSIDL_FLAG_CREATE, nullptr, 0, szPath);
path = szPath;

**Comment by tore29** [comment]
@Gerwin2k The fix should be merged now. Can you test on your end?

**Comment by Gerwin2k** [comment]
@tore29 I just tested current VanillaRA and TD. They both work fine under Windows XP. Thanks for making and merging the commit!
