### ISSUE TITLE
TD - Loading save 'changes enemy side'

### ISSUE THREAD

**Issue by Gerwin2k** [TheAssemblyArmada/Vanilla-Conquer#637]
Regarding, dev packaged 656104a, VanillaTD

When playing covert ops GDI Infiltrated!, save and load the game. The NOD enemy will have turned from red color to blue on the radar. Also, after doing that, I noticed the guard towers sometimes let enemy engineers just walk by.

**Comment by OmniBlade** [comment]
Thanks for the report, it seems unlikely that the changes in that PR are responsible, have you tested a build from the vanilla branch to see if this issue is present there and has this worked previously for you? Also, which platform and build type are you testing on?

**Comment by Gerwin2k** [comment]
First, I was mistakenly thinking this 'infiltrated!' radar color bug was recent save/load-commit related. But indeed, it is not new at all. Like builds from 5 january 2021 show it as well. I just tested like 6 debug+release variants of Win32 VanillaTD, and they all do this.

Knowing this, I regret making this ticket. 

The Engineers thing may be related, maybe old, maybe new, but that would be much harder to test, as it doesn't happen as readily.

**Comment by OmniBlade** [comment]
The radar colour thing is definitely a bug, so opening the ticket was the right thing to do. Not sure what causes it as of yet, but at least we have a record of it.

**Comment by giulianobelinassi** [comment]
I've fixed several "radar weirdness" on #655. This bug is still triggered if you save & reload the game, so it may be an issue in the saving system.

Engineers trying to capture guard towers is a bug in the original game.

**Comment by Gerwin2k** [comment]
Thanks giulianobelinassi!
The radar color fix works well over here.
