### ISSUE TITLE
Crash on unit repair.

### ISSUE THREAD

**Issue by OmniBlade** [TheAssemblyArmada/Vanilla-Conquer#643]
Its has been reported that vanilltd crashes when attempting to repair a unit on the service depo if the player has money and the unit is damaged.

**Comment by Northfear** [comment]
Found the source of the issue
https://github.com/TheAssemblyArmada/Vanilla-Conquer/blob/vanilla/tiberiandawn/building.cpp#L4602
There's an attempt to open `RawFileClass` with name repair1.aud, which doesn't exists, so everything just crashes at `Raw_Seek`.
Looks like repair sound wasn't in original TD anyway, so maybe reverting it back is the right way to go?

**Comment by hifi** [comment]
@Northfear would you want to submit a PR with `#ifdef REMASTER_BUILD` around that code?

We don't revert Remaster changes but guard them so the Remaster version works like expected.

**Comment by Northfear** [comment]
Sure, I'll submit it in a minute

**Comment by tore29** [comment]
This one is odd. C&C usually fails gracefully in such cases at least with animations and graphics.

**Comment by giulianobelinassi** [comment]
Side note: DOS C&C actually uses this sound. Since now we support C&C DOS files and this sound is played, fixing it by guarding for REMASTER_BUILD may be incorrect.
