### ISSUE TITLE
[TD] Obelisks lasers are not undraw after shoot

### ISSUE THREAD

**Issue by giulianobelinassi** [TheAssemblyArmada/Vanilla-Conquer#656]
Obelisks lasers are only undrawn from the screen when they are destroyed.

**Comment by hifi** [comment]
Wonder if this happens with remaster and the legacy renderer that the dll provides or if they just had their own version if it overlayed.

**Comment by giulianobelinassi** [comment]
On techno.cpp, at `TechnoClass::Draw_It`:

```
    if (LineFrame < LineMaxFrames) {
        // Only draw the last line for virtual window
        int start_line = (window == WINDOW_VIRTUAL) ? max(0, LineCount - 1) : 0;
        for (int i = start_line; i < LineCount; i++) {
            CC_Draw_Line(
                Lines[i][0], Lines[i][1], Lines[i][2], Lines[i][3], (unsigned char)Lines[i][4], LineFrame, window);
        }
        if (window == WINDOW_VIRTUAL) {
            LineFrame++;
        }
    }
```

This `CC_Draw_Line` call is what draws the laser warhead. It should increment if window == WINDOW_VIRTUAL, but this function is only called with WINDOW_TACTICAL. Commenting the check fixes the problem.

**Comment by hifi** [comment]
Yeah, the whole concept of a virtual window is for the remasters. Good find!
