### ISSUE TITLE
[Remaster] Building placement check is skipping two lines

### ISSUE THREAD

**Issue by giulianobelinassi** [TheAssemblyArmada/Vanilla-Conquer#665]
![Untitled](https://user-images.githubusercontent.com/7212952/125206361-486ef800-e25d-11eb-8452-c9490461bb42.png)

**Comment by giulianobelinassi** [comment]
This happens when MEGAMAPS is enabled

**Comment by mvdhout1992** [comment]
IIRC this was an issue with megamaps too with the vanilla-conquer TD version standalone (original game graphics).

**Comment by OmniBlade** [comment]
Did you copy the files from resources/remaster_mods/Vanilla_TD? That constants xml file needs to be present to prevent this in the remaster GUI.
