### ISSUE TITLE
[RA] Engineer do not capture ally building

### ISSUE THREAD

**Issue by giulianobelinassi** [TheAssemblyArmada/Vanilla-Conquer#668]
https://www.youtube.com/watch?v=4mLuMNde-u4

**Comment by hazelnot** [comment]
I'm pretty sure this isn't a bug lmao, entering an ally's building with an engineer _should_ repair it without capturing

**Comment by tore29** [comment]
Don't think this is a bug. Engineers should repair allied structures, not capture them.

**Comment by OmniBlade** [comment]
Isn't the issue that if someone allies with me but I don't reciprocate, I should be able to capture their stuff still but the bug prevents it?

**Comment by hazelnot** [comment]
> Don't think this is a bug. Engineers should repair allied structures, not capture them.

I was confused about this too, but no, because they meant a one-sided alliance request from someone else

**Comment by OmniBlade** [comment]
Does anyone know if the same issue affects TD out of interest?

**Comment by giulianobelinassi** [comment]
I don't think so. TD engineers can't repair buildings.

**Comment by OmniBlade** [comment]
Turns out this was already fixed by WW, but never implemented as it would cause desyncs with clients on other versions of the exe without it based on comments in defines.h for FIXIT_ENGINEER_CAPTURE.
