### ISSUE TITLE
[TD] DOS mode breaks drop down menus

### ISSUE THREAD

**Issue by hifi** [TheAssemblyArmada/Vanilla-Conquer#684]
There's no arrow on the right drawn to click on. This is with demo patched freeware so it might be missing data as well. 

For overall usability we should make the whole input area clickable regardless of the arrow.

The skirmish side selection is a fast test case.

**Comment by giulianobelinassi** [comment]
The right scroll bar is also missing. It may be related to this issue.

**Comment by giulianobelinassi** [comment]
Fixed in 9bac210
