### ISSUE TITLE
[TD] 320x200: Broken score screen

### ISSUE THREAD

**Issue by giulianobelinassi** [TheAssemblyArmada/Vanilla-Conquer#685]
The scorescreen fonts are being displayed on incorrect places. This is most likely an incorrect `resfactor` value in some function.

**Comment by hifi** [comment]
The kill bars are not drawn either.

**Comment by giulianobelinassi** [comment]
Fixed in fbfa16a1b20ede93ed415f41916bdcafdf7123a0
