### ISSUE TITLE
[VanillaMix] Packing directories doesn't work on Windows

### ISSUE THREAD

**Issue by anpage** [TheAssemblyArmada/Vanilla-Conquer#686]
The vanillamix tool doesn't pack directories of files into a .MIX file correctly on Windows. I did some debugging and found that the `opendir()` and `__internal_opendir()` functions in the miniposix library are flawed.

I don't know if it's still relevant to modern Windows, but I was only able to get this part of the tool to work by removing the `\\?\` it tries to add to the beginning of the directory path.

I can submit a PR for this, but I don't know if removing that suffix entirely is the "correct" way to fix it.

**Comment by anpage** [comment]
Found out that full paths work, so I made a small PR (#687) to make sure they're always full on Windows.

**Comment by OmniBlade** [comment]
Thanks for the bug report, which version of Windows are you working with as the \\?\ extension causes it to break the traditional windows path limit of 256 characters on recent versions.

**Comment by OmniBlade** [comment]
Looks like the prefix doesn't work with relative paths which is why it fails, thank you for the PR, but I would rather fix this in the library so the function behaves as expected.

**Comment by anpage** [comment]
Wanting to fix it in the lib is fair, but maybe the best way to fix it would be to move the call to `_fullpath()` inside the library? That way you can still avoid the 256 char limitation.

**Comment by OmniBlade** [comment]
That is a good point, would need to convert the string to wide first and call _wfullpath instead though as only very recent windows builds consider the narrow versions utf8. I'll revise my PR when I get chance to properly support that.

**Comment by OmniBlade** [comment]
Okay, PR #688 has been updated to use a call to _wfullpath to retrieve the absolute path to the directory. I've done some basic testing on it if you also want to give it a test and see how it works for you.

**Comment by OmniBlade** [comment]
Fixed with the merge of #688.
