### ISSUE TITLE
Binaries of CI should be stored

### ISSUE THREAD

**Issue by ghost** [TheAssemblyArmada/Vanilla-Conquer#69]
It would allow to build new exe (with extra patches) without need to understand build system.

Easy way is store on appveyor site. (but it has only 6m lifetime) 
Another way (which I recommend) is to store on bintray. (or similar site)

Examples:
https://github.com/bvschaik/julius/blob/master/.appveyor.yml
https://github.com/GTAmodding/re3/blob/master/.appveyor.yml

**Comment by OmniBlade** [comment]
We'll look at the storing of artifacts when we setup some github workflows.
