### ISSUE TITLE
Change data Dir

### ISSUE THREAD

**Issue by Exarkuniv** [TheAssemblyArmada/Vanilla-Conquer#693]
I was able to build this on my Pi4 ( with help) and it seems to try to start.  I need the correct data from the CDs, which i dont have at the moment.

when i start the game i get this

INFO : Searching the following paths for path config data:
  argv: '/opt/retropie/ports/vanillacc/tiberian dawn'
  binary: '/opt/retropie/ports/vanillacc/tiberian dawn'
  default data: '/opt/retropie/ports/vanillacc/share/vanillatd'
  default user: '/home/pi/.config/vanilla-conquer/vanillatd'
INFO : Read only data directory is set to '/opt/retropie/ports/vanillacc/share/vanillatd'
INFO : Read/Write user data directory is set to '/opt/retropie/ports/vanillacc/tiberian dawn'
DEBUG: C&C95 - Creating main window.

here i can see where it is looking for the game data. 
My questionnis there a way to change that so i can tell it to look somewhere else

im building this for my RetroPie setup so i like to keep the games in the same spot

**Comment by hifi** [comment]
If you have redalert.ini or conquer.ini in the binary directory it will work in legacy mode where all data is in the same directory.

**Comment by OmniBlade** [comment]
Hello. The game will search each of those default folders in turn for a conquer.ini file (or redalert.ini for vanillara) if found, it will check for a `[Paths]` section and will check for DataPath= and UserPath= to set the read only data path and the read/write paths respectively. As @hifi says, it will default to having both those paths set to the binary directory (as the original game did) if it finds the config file next to the binary.

**Comment by Exarkuniv** [comment]
yes i see the conquer.ini, but there is nothing in it about the Data dir

i do have the binary in with the install game files, and the cds. but they are in ISO format. so a error comes up saying that it cant find the cds.
i was reading some other issues. that i have to unpack the CDs?

**Comment by OmniBlade** [comment]
You need to add those sections yourself, something like the following:

```
[Paths]
DataDir=/home/username/C&C95
UserDir=/home/username/C&C95_data
```

You also need to unpack the CDs as well, https://github.com/TheAssemblyArmada/Vanilla-Conquer/wiki/Installing-VanillaTD shows what the directory structure should look like.

**Comment by Exarkuniv** [comment]
@OmniBlade thank you for all of that

while i was looking for the conquer.ini file i came across 2 of them. one is in the game data folder from when i installed the game on my PC and the other is "/home/pi/.config/vanilla-conquer/vanillatd".

guessing that the one in the .config is the one i need to edit?

**Comment by Exarkuniv** [comment]
So i made the conquer.ini look like this 
```
[Paths]
DataDir="home/pi/RetroPie/roms/portsC&C95
UserDir=/home/pi/RetroPie/C&C95_data

[Intro]
PlayIntro=no
```

and this is what i get when i try and running the game to see if the paths took

```
INFO : Searching the following paths for path config data:
  argv: '/opt/retropie/ports/vanillacc/tiberian dawn'
  binary: '/opt/retropie/ports/vanillacc/tiberian dawn'
  default data: '/opt/retropie/ports/vanillacc/share/vanillatd'
  default user: '/home/pi/.config/vanilla-conquer/vanillatd'
INFO : Read only data directory is set to '/opt/retropie/ports/vanillacc/share/vanillatd'
INFO : Read/Write user data directory is set to '/home/pi/.config/vanilla-conquer/vanillatd'
DEBUG: C&C95 - Creating main window.

DEBUG: C&C95 - Initialising audio.

DEBUG: C&C95 - Setting video mode. 
```
does not look like it took it

**Comment by Exarkuniv** [comment]
i have tryed everything i can think of to get it to change the dir of the game. 
no luck. 
ill just work on figuring out how to make it work with my setup

BTW TD boots and plays great on the pi4 the little i have messed with
