### ISSUE TITLE
VanillaRA error when launched 

### ISSUE THREAD

**Issue by Exarkuniv** [TheAssemblyArmada/Vanilla-Conquer#695]
i have compiled this on my Pi4 with help of course. It builds both VanillaTD and RA fine with out errors
and im able to start VanillaTD with out issue
when i start VanillaRA though i get there error

```
INFO :   scaler set to 'nearest'
assert 'ok' failed at line 2362 in module /home/pi/RetroPie-Setup/tmp/build/vanillacc/Vanilla-Conquer-latest/redalert/init.cpp.
DEBUG: Prog_End()
DEBUG: assert 'ok' failed at line 2362 in module /home/pi/RetroPie-Setup/tmp/build/vanillacc/Vanilla-Conquer-latest/redalert/init.cpp.

assert 'ok' failed at line 2367 in module /home/pi/RetroPie-Setup/tmp/build/vanillacc/Vanilla-Conquer-latest/redalert/init.cpp.
DEBUG: Prog_End()
DEBUG: assert 'ok' failed at line 2367 in module /home/pi/RetroPie-Setup/tmp/build/vanillacc/Vanilla-Conquer-latest/redalert/init.cpp.
```

no idea whats going on

i will rerun my install script and see if i can pull any errors to help out

this is the only error i get
```
/home/pi/RetroPie-Setup/tmp/build/vanillacc/Vanilla-Conquer-latest/redalert/wolstrng.cpp:26:49: note: #pragma message: ...Building English version...
 #pragma message("...Building English version...")
```

**Comment by hifi** [comment]
It means your Red Alert data is incomplete, it's missing `HIRES.MIX` (which should be in `REDALERT.MIX` IIRC).

See the wiki for data installation instructions.

**Comment by Exarkuniv** [comment]
> 
> 
> It means your Red Alert data is incomplete, it's missing `HIRES.MIX` (which should be in `REDALERT.MIX` IIRC).
> 
> See the wiki for data installation instructions.

thank you, i though it was a error with the binary. since it was giving me a different error then VanillaTD when i started it. 
but i did what you said and it works perfect. 
thank you
