### ISSUE TITLE
[TD] Score screen appears to freeze when waiting for name.

### ISSUE THREAD

**Issue by Allen262** [TheAssemblyArmada/Vanilla-Conquer#699]
The VTD score screen appears to freeze when waiting for name to be type at the end of missions. If you type a letter the scree will unfreeze for a frame or two than looks frozen again. Sound is playing fine and it just the lack of animated clock and a blinking "_" cursor. Tested with R698 B7B8B62

**Comment by OmniBlade** [comment]
Can you confirm which platform you experienced this issue on?

**Comment by Allen262** [comment]
Windows 10
