### ISSUE TITLE
Vanilla TD: Can see what the enemy has explored on the minimap in MP game

### ISSUE THREAD

**Issue by tore29** [TheAssemblyArmada/Vanilla-Conquer#720]
![image](https://user-images.githubusercontent.com/3741094/146692283-2ebd74da-2c5d-4cc5-8a85-1d495e3a526a.png)

Steps to reproduce
1. Play MP with another player
2. Build radar
3. See what the enemy does and has done...

Kinda interesting feature for a C&C like game, but for C&C this is quite incorrect.

**Comment by OmniBlade** [comment]
This is only reflected in the radar and not the shroud yes?

**Comment by tore29** [comment]
Indeed @OmniBlade
