### ISSUE TITLE
(TD and RA) right keys treated differently than left keys

### ISSUE THREAD

**Issue by tore29** [TheAssemblyArmada/Vanilla-Conquer#724]
In Vanilla pressing right control causes units to be deselected instead of switching the cursor to force fire as right control does. 

To be consistent with the original games right keys should do the same as left keys by default.

This affects shift and control.

**Comment by giulianobelinassi** [comment]
May be a SDL issue.

**Comment by OmniBlade** [comment]
Looks like its an issue with how @hifi set up the mapping of SDL to KN and KA values by going via VK mappings. I'm inclined to fix this by just ifdeffing different definitions of the KA and KN stuff with direct SDL value mappings.
