### ISSUE TITLE
[TD] Orca ammo reload on helipad takes too long 

### ISSUE THREAD

**Issue by Gerwin2k** [TheAssemblyArmada/Vanilla-Conquer#726]
Orca ammo reload on helipad takes too long  These units are currently quite useless.
Should be around 9 seconds for a 5-pip reload, at average game speed. As timed in C&C Gold.

Relevant section is in building.cpp, close to line 4688, if (Transmit_Message(RADIO_RELOAD) != RADIO_ROGER) {

This is a regression. For reference the code of 01-2021, without this issue:
```
                } else {
                    int time = Bound(Fixed_To_Cardinal(TICKS_PER_SECOND, House->Power_Fraction()), 0, TICKS_PER_SECOND);
                    time = (TICKS_PER_SECOND * 3) - time;
                    IsReadyToCommence = false;
                    return (time);
                }
```

Current code, with this issue:
```
                } else {
                    fixed pfrac = Saturate(House->Power_Fraction(), 1);
                    if (pfrac < fixed::_1_2)
                        pfrac = fixed::_1_2;
                    int time = Inverse(pfrac) * TICKS_PER_MINUTE;
                    IsReadyToCommence = false;
		    return (time);
                }
```
Should it be "TICKS_PER_MINUTE / 60", or / 100?
Both are pretty close to what I would expect.

**Comment by OmniBlade** [comment]
This is just poorly ported by me from RA I'm afraid, in RA a rules.ini multiplier is also involved which brings its to your expected reload rate but that doesn't exist (yet at least) in TD. I'll whip up a provisional fix to act as a stop gap.

**Comment by OmniBlade** [comment]
Could you check a build of #728 from its build artifacts and let me know if that resolves the issue for you? The timing should now match the original.

**Comment by Gerwin2k** [comment]
I just tried the artifact build, and timed it as an 8 second reload at average game speed. Thanks for fixing this in such short notice.
