### ISSUE TITLE
[TD] Can I jump to a specific level if my save file is corrupted? 

### ISSUE THREAD

**Issue by xcom169** [TheAssemblyArmada/Vanilla-Conquer#741]
Hello All!

Can I jump to a specific level if my save file is corrupted because of a revision change? 
Any cheat to jump to a level differ from level 1 ? 

Thanks a lot

**Comment by OmniBlade** [comment]
Not at the moment, though you could run the game with -EDITOR to load into the editor interface then use that to load any level you want and then play it. Unfortunately more save game breakages are likely until with have a format that we can try and make forward compatible with future changes.

**Comment by xcom169** [comment]
Thanks!
