### ISSUE TITLE
Reimplement timers in a portable manner

### ISSUE THREAD

**Issue by hifi** [TheAssemblyArmada/Vanilla-Conquer#79]
Later games used to poll the system time on request and calculate the ticks based on frequency. We should probably do the same.

This is up for grabs and should be rather simple to implement. @OmniBlade noted that the C++ chrono could be used for this.

**Comment by OmniBlade** [comment]
Isn't this taken care of by #122?

**Comment by hifi** [comment]
It indeed is.
