### ISSUE TITLE
Compilation error for localized builds

### ISSUE THREAD

**Issue by laenion** [TheAssemblyArmada/Vanilla-Conquer#851]
@MLipfert1: According to 2de360f033d6cde8bb131e6ab31a6f6fab997f92 using the `FRENCH` and `GERMAN` build options should be working without build errors.

However for me the French build fails with the following messages:

```
[ 69%] Built target VanillaRA
/home/ignaz/Downloads/sources/Open-Source-Engines/Vanilla-Conquer/tiberiandawn/intro.cpp: In function 'void Choose_Side()':
/home/ignaz/Downloads/sources/Open-Source-Engines/Vanilla-Conquer/tiberiandawn/intro.cpp:167:38: error: 'TXT_GDI_NAME2' was not declared in this scope; did you mean 'TXT_GDI_NAME'?
  167 |     Alloc_Object(new ScorePrintClass(TXT_GDI_NAME2, 0, 187, _yellowpal));
      |                                      ^~~~~~~~~~~~~
      |                                      TXT_GDI_NAME
/home/ignaz/Downloads/sources/Open-Source-Engines/Vanilla-Conquer/tiberiandawn/mapsel.cpp: In function 'void Map_Selection()':
/home/ignaz/Downloads/sources/Open-Source-Engines/Vanilla-Conquer/tiberiandawn/mapsel.cpp:861:38: error: 'TXT_MAP_NEXT_MISS2' was not declared in this scope; did you mean 'TXT_MAP_NEXT_MISSION'?
  861 |     Alloc_Object(new ScorePrintClass(TXT_MAP_NEXT_MISS2, 0, 180, _greenpal));
      |                                      ^~~~~~~~~~~~~~~~~~
      |                                      TXT_MAP_NEXT_MISSION
```

Building the German version also fails, but only with the later definition not being found.

Am I missing something here? Where should this definition come from?

**Comment by MLipfert1** [comment]
Compiling will only work for Red Alert so far, not for Tiberian Dawn. The latter one is not adjusted yet. I tried it, but there is more to do, as it was for Red Alert. The localized versions of Tiberian Dawn, I have tried, had mixed up text strings. Seems that some of the mix-files of the german Tiberian Dawn version have a different structure than the english one.

**Comment by laenion** [comment]
Ah, thanks a lot, I was missing the information that this is only working for Red Alert so far - thanks for clarification!
