### ISSUE TITLE
[TD] Dino Mission Saves Are Broken Because AreThingiesEnabled Isn't Saved

### ISSUE THREAD

**Issue by ChthonVII** [TheAssemblyArmada/Vanilla-Conquer#853]
If you save during a dino mission and reload in context where AreThingiesEnabled isn't expressly set, then it will revert to the default value of 0. The variable is checked in places that impact gameplay.

[The fix](https://github.com/ChthonVII/CnC_Remastered_Collection/commit/0c35e0e4c1094eba676882ebc9f0549a8ae49f4f) is to add it to the save file.

**Comment by Gerwin2k** [comment]
As of this date 05-2023 the variable "AreThingiesEnabled" is not present in the Vanilla Conquer TiberianDawn source code. I don't know if it was renamed or made obsolete...

**Comment by Gerwin2k** [comment]
There is a typo there in the fix, with an 'o' at the end of AreThingiesEnabled.
