### ISSUE TITLE
Game Doesn't Close, Process Still runs in background.

### ISSUE THREAD

**Issue by OpenRift412** [TheAssemblyArmada/Vanilla-Conquer#917]
I have no idea why it's doing this, but when I close the game, I found that it's still running in the background, and I didn't notice until my whole PC started slowing down because there were several instances of VanillaTD running in the background.

**Comment by OmniBlade** [comment]
I've not experienced this myself locally unfortunately, does it always do this for you or only after a certain set of actions in game or if you exit in some particular way?

**Comment by OpenRift412** [comment]
> I've not experienced this myself locally unfortunately, does it always do this for you or only after a certain set of actions in game or if you exit in some particular way?

It does this every time I close the game.

**Comment by tore29** [comment]
Can confirm this. Happens only with VanillaTD, not VanillaRA.

![image](https://github.com/TheAssemblyArmada/Vanilla-Conquer/assets/3741094/0621789a-6ce9-4e32-a366-95fb6aaa355d)

**Comment by Gerwin2k** [comment]
I see the problem too, in WIN32. 
Traced it to this recent change of march 2023, which added Sound_End at exit.
https://github.com/TheAssemblyArmada/Vanilla-Conquer/commit/52a23fcad56197428a8b0f37d8d00ddd783e2472
What strikes me as odd, is that before this commit there was an elif (Else if) compiler directive. In case of both SDL and WIN32 being defined, it behaved differently.

**Comment by OmniBlade** [comment]
A fix for this has been merged, feel free to reopen if it is still and issue.
