### ISSUE TITLE
TD: Troop Voices missing when giving orders

### ISSUE THREAD

**Issue by OpenRift412** [TheAssemblyArmada/Vanilla-Conquer#920]
For some reason, when selecting and ordering troops in Tiberian Dawn, voices ("yes sir", "affirmative") won't play. I don't know if it's a setting that I have set or something, but it seems to work just fine in C&C95 v1.06 on pretty much the same config file.

**Comment by OpenRift412** [comment]
It also seems to work just fine in with my DOS install, for some reason.

**Comment by tore29** [comment]
Works fine. Are you using 1.06c data on Vanilla Conquer?

**Comment by OpenRift412** [comment]
> Works fine. Are you using 1.06c data on Vanilla Conquer?

Yes, I am.

**Comment by tore29** [comment]
That isn't a supported install right now. You need the original 1.04 version from a C&C95 CD/CD image.

1.06x is an unofficial version by Nyerguds. It's data differs from the original.

**Comment by OpenRift412** [comment]
> That isn't a supported install right now. You need the original 1.04 version from a C&C95 CD/CD image.
> 
> 1.06x is an unofficial version by Nyerguds. It's data differs from the original.

Interesting. Thanks for letting me know.

**Comment by OmniBlade** [comment]
Closing as wontfix since we don't support unofficially packaged data.
