### ISSUE TITLE
[TD] Garbage pixels on bottom and right-hand side of radar

### ISSUE THREAD

**Issue by hazelnot** [TheAssemblyArmada/Vanilla-Conquer#922]
Garbage pixels appear on the bottom and right-hand side edges of the TD radar. Just 1 pixel wide lines of them, at the very edges of the radar area. Haven't tested on other platforms, but it happens on Linux.

![Screenshot from 2023-05-18 21-46-29](https://github.com/TheAssemblyArmada/Vanilla-Conquer/assets/10992973/4c51d595-81ba-4a9e-b7be-1acc2e2a0508)

**Comment by OmniBlade** [comment]
Fixed in #1000
