### ISSUE TITLE
[TD] Skirmish computer opponent does not produce vehicles

### ISSUE THREAD

**Issue by Gerwin2k** [TheAssemblyArmada/Vanilla-Conquer#928]
Base building of Skirmish computer opponents is significantly improved, but unit production is currently useless. Even with 7 refineries making money and 3 factories/airstrips you will see the AI producing maybe 1 vehicle throughout an entire game. Especially when not under attack. Some infantry is produced.

I tried to trace the cause, and it seems Control.MaxUnit is not set properly. I have not investigated it too deeply, because seemingly several sections in house.cpp, which set Control.MaxUnit, are actually Red Alert specific and not (yet) used for TD.

A quick hack-fix is setting it to 150 right before the check that prevents the units from being build, like so:

house.cpp line 6398
```
int HouseClass::AI_Unit(void)
{

    if (BuildUnit != UNIT_NONE)
        return (TICKS_PER_SECOND);

    // GB 2023, not quite sure why I have to put this here, but otherwise the AI will build maybe 1 unit max. 
    Control.MaxUnit=150;

    if (CurUnits >= Control.MaxUnit)
        return (TICKS_PER_SECOND);
```

**Comment by tore29** [comment]
Interesting. I've been looking into this myself, but never really found anything useful other than a suspicion that a value wasn't being assigned properly. I suspect the value is supposed to be assigned somewhere else. Perhaps through an ini setting? I've seen some references to infantry like that.

**Comment by tore29** [comment]
With the merging of #930 this should be fixed :)

**Comment by Gerwin2k** [comment]
I just tried the latest build: vanilla-conquer-win-gcc-i686-a36cba3.zip 
The computer builds vehicles now.
Thanks!
