### ISSUE TITLE
Rename "Normal" Difficulty to "Original"

### ISSUE THREAD

**Issue by OpenRift412** [TheAssemblyArmada/Vanilla-Conquer#988]
I think this would be a better descriptor for new players seeking a more authentic gameplay experience.

**Comment by OmniBlade** [comment]
"Easy", "Normal" and "Hard" are standard namings for difficulty levels and matches the names given in Red Alert which doesn't have a single "Original" difficulty.

**Comment by OpenRift412** [comment]
> "Easy", "Normal" and "Hard" are standard namings for difficulty levels and matches the names given in Red Alert which doesn't have a single "Original" difficulty.

I moreso meant for Tiberian Dawn, since that never had a difficulty slider to begin with.
